#! /bin/csh
# @(#) CSM SCCS /u/sys/src/usr/local/bin/vitutor/SCCS/s.vitutor 1.8 91/12/02 11:46:50

set FROM = "/usr/local/bin/tutor.vi"
set TO = "${HOME}/tutor.vi"
set OLD = "${TO}.old"

if ($TERM == "dumb") then
	echo "You must use a CRT terminal AND the system must know what type"
	echo "terminal you are using in order to use 'vi' effectively."
	echo "When you see the 'TERM = (dumb)' prompt during login, you"
	echo "need to enter the type of CRT terminal you are using."
	echo "For example, if you are using a vt100 terminal, then enter"
	echo "'vt100' in response to the 'TERM = (dumb)' prompt."
	echo "If you don't know what to enter for the terminal you are,"
	echo "using, then try 'vt52' and see if that works ok."
	echo ""
	echo "Now you need to log out and start over, using a CRT terminal"
	echo "and entering the correct terminal type when you login"
	exit
endif
if (-e $TO ) then
	mv -i $TO $OLD
endif
cp  $FROM $TO
vi $TO < /dev/tty
exit
